from .brawlers_view import BrawlersView
from .forgot_view import ForgotView
from .home_view import HomeView
from .login_view import LoginView
from .members_view import MembersView
from .no_club_view import NoClubView
from .past_members_view import PastMembersView
from .register_view import RegisterView
from .valorate_view import ValorateView
